/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProgettoCasotto;

import ProgettoCasotto.Spiaggia.*;

public class App {

    public static void main(String[] args) {

//        Chalet chalet=new Chalet("lollo");
//
//        //creo una spiaggia
//        Spiaggia spiaggia = new Spiaggia("BarracudaSpiaggia");
//        spiaggia.setNumOmbrelloni(50);
//        spiaggia.setNumSdraio(10);
//
//        //creo una prenotazione
//        String IDPrenotazione="50";
//        Prenotazione prenotazione=new Prenotazione(IDPrenotazione,15,25);
//        spiaggia.addPrenotazione(prenotazione);
//        spiaggia.addOmbrelloneToPrenotazione(IDPrenotazione,"4");
//        spiaggia.addOmbrelloneToPrenotazione(IDPrenotazione,"5");
//        spiaggia.confermaAvvenutoPagamentoPrenotazione(prenotazione);
//        spiaggia.pagaPrenotazione(prenotazione);
//
//        //creo un'altra prenotazione
//        String IDAltraPrenotazione="90";
//        Prenotazione prenotazione2=new Prenotazione(IDAltraPrenotazione,15,25);
//        spiaggia.addPrenotazione(prenotazione2);
//        spiaggia.addOmbrelloneToPrenotazione(IDAltraPrenotazione,"20");
//        spiaggia.pagaPrenotazione(prenotazione2);
//
//        //provo la modifica di un periodo
//        Prenotazione prenotazione3=new Prenotazione("70",26,30);
//        spiaggia.addPrenotazione(prenotazione3);
//        spiaggia.addOmbrelloneToPrenotazione("70","10");
//        spiaggia.pagaPrenotazione(prenotazione3);
////        spiaggia.modificaPrenotazione(prenotazione2);
//
//        //provo la modifica del numero di sdraio
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"0");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"1");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"2");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"3");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"4");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"5");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"6");
//        spiaggia.addSdraioToPrenotazione(IDPrenotazione,"7");
////
////        spiaggia.modificaPrenotazione(prenotazione2);
////        spiaggia.getPrenotazione();
//
//        //provo la modifica del numero di ombrelloni
////        spiaggia.modificaPrenotazione(prenotazione2);
//
//
//        Prenotazione prenotazione4=new Prenotazione("40",26,30);
//        spiaggia.addPrenotazione(prenotazione4);
//        spiaggia.addOmbrelloneToPrenotazione("40","9");
//        Prenotazione prenotazione5=new Prenotazione("60",26,30);
//        spiaggia.addPrenotazione(prenotazione5);
//        spiaggia.addOmbrelloneToPrenotazione("60","1");
//        Prenotazione prenotazione6=new Prenotazione("650",26,30);
//        spiaggia.addPrenotazione(prenotazione6);
//        spiaggia.addOmbrelloneToPrenotazione("650","15");
//        spiaggia.pagaPrenotazione(prenotazione6);
//        spiaggia.cambiaStatoPrenotazioneInBaseAlTempo();
//        chalet.addAreaAttivita("Campo Beach Volley");
//        chalet.createAttivita("torneoBeach", 20,10,11);
//        chalet.StampaChalet();
//        spiaggia.getPrenotazione();

        //modifico AltraPrenotazione
//        spiaggia.getStatoSpiaggia();
//       //l'utente inserisce il periodo in cui vuole pernotarsi
//        System.out.println("inserire la data di inzio periodo");
//        Scanner scanner = new Scanner(System.in);
//        int dataInizio = scanner.nextInt();
//        System.out.println("inserire la data di fine periodo");
//
//        int dataFine = scanner.nextInt();
//        if(!spiaggia.getOmbrelloniLiberi(dataInizio,dataFine).isEmpty()) {
//            //stampo la lista degli ombrelloni liberi
//            System.out.println("lista ombrelloni liberi");
//            for (Ombrellone ombrellone : spiaggia.getOmbrelloniLiberi(dataInizio, dataFine)) {
//                System.out.print("|" + ombrellone.getID());
//            }
//            System.out.println("\n------------------------");
//            //creo una prentazione vuota
//            int IDPrenotazione = 50;
//            spiaggia.addPrenotazione(Integer.toString(IDPrenotazione), dataInizio, dataFine);
//            //l'utente sceglie l'ombrellone
//            System.out.println("scegli l'ombrellone");
//            int IdOmbrellone = scanner.nextInt();
//            spiaggia.addOmbrelloneToPrenotazione(Integer.toString(IDPrenotazione), Integer.toString(IdOmbrellone));
//            System.out.println("lista Sdraio liberi");
//            for (Sdraio sdraio : spiaggia.getSdraioLiberi(dataInizio, dataFine)) {
//                System.out.print("|" + sdraio.getID());
//            }
//            System.out.println("\n------------------------");
//            System.out.println("scegli lo sdraio");
//            int IdSdraio = scanner.nextInt();
//            spiaggia.addSdraioToPrenotazione(Integer.toString(IDPrenotazione), Integer.toString(IdSdraio));
//            System.out.println(spiaggia.getPrenotazione());
//            for (Ombrellone ombrellone : spiaggia.getOmbrelloniOccupati(dataInizio, dataFine)) {
//                System.out.println(ombrellone.getID());
//            }
//            System.out.println("gli ombrelloni liberi sono :");
//            for (Ombrellone ombrellone : spiaggia.getOmbrelloniLiberi(dataInizio, dataFine)) {
//                System.out.println(ombrellone.getID());
//            }
//
//            //provo ad cercare un ombrellone in un intervallo di tempo in cui risulterebbe occupato
//            System.out.println("inserisco un periodo di tempo compreso in quello precedente");
//            System.out.println("inserire la data di inzio periodo");
//            dataInizio = scanner.nextInt();
//            System.out.println("inserire la data di fine periodo");
//            dataFine = scanner.nextInt();
//
//            System.out.println("lista ombrelloni liberi");
//            for (Ombrellone ombrellone : spiaggia.getOmbrelloniLiberi(dataInizio, dataFine)) {
//                System.out.print("|" + ombrellone.getID());
//            }
//            System.out.println("\n------------------------");
//
//            IDPrenotazione = 51;
//            spiaggia.addPrenotazione(Integer.toString(IDPrenotazione), dataInizio, dataFine);
//            System.out.println("scegli l'ombrellone");
//            IdOmbrellone = scanner.nextInt();
//            spiaggia.addOmbrelloneToPrenotazione(Integer.toString(IDPrenotazione), Integer.toString(IdOmbrellone));
//            System.out.println(spiaggia.getPrenotazione());
//        }
//        //creo un 'attivita
//        System.out.println(spiaggia.creaAttivita("torneo",40,15,16));
//        System.out.println(spiaggia.prenotaAttivita("torneo",30));
//        spiaggia.getAttivita();
//
//        Menu menu=new Menu(2);
//        Bevanda bevanda1=new Bevanda(1,"cocacola");
//        Bevanda bevanda2=new Bevanda(2,"fanta");
//        menu.inserisciBevandaNelCatalogo(bevanda1,40);
//        menu.inserisciBevandaNelCatalogo(bevanda2,20);
//        Bar bar=new Bar("Barra",menu);
//        bar.selectBevanda(1,bevanda1,10);
//        bar.selectBevanda(2,bevanda1,30);
//        bar.selectBevanda(1,bevanda2,19);
//        System.out.println("il bar viene inserito");
//        System.out.println(chalet.addBar(bar));
//        bar.stampaListaOrdinazioni();
//        bar.getInventario();
//        chalet.StampaChalet();
        gestoreDB gestore=new gestoreDB();
    }

}
